spring.application.name=api
server.port=9003

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

minio.endpoint=http://localhost:9000
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket=hephaestus-worlds

hephaestus.api.plugin-key=${HEPHAESTUS_PLUGIN_KEY}

hephaestus.jwt.expiration=3600
hephaestus.jwt.secret=${JWT_SECRET}

hephaestus.admin.username=${HEPHAESTUS_ADMIN_USERNAME}
hephaestus.admin.password=${HEPHAESTUS_ADMIN_PASSWORD}

logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG